# pbcopy 連携 (set-clipboard は共通の .tmux.conf 側に集約)
set -g copy-command 'pbcopy'

set -g status-right '#(cat ~/.pomo_stat) #[fg=yellow,bold]#(uptime | cut -d ',' -f 3- | cut -d ':' -f 2-) #[fg=cyan,bold]%m/%d(%a) %H:%M'
